version: "3.8"

services:
  db:
    image: postgis/postgis:13-3.1
    container_name: postgis-database
    restart: always
    environment:
      POSTGRES_DB: noaa_database
      POSTGRES_PASSWORD: your_secure_password
      POSTGRES_USER: noaa_user
    ports:
      - "5432:5432"
    volumes:
        - db-data:/var/lib/postgresql/data
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql




volumes:
  db-data:
